
# main keys, values can be overwritten via command line arguments

debug: false # enables debug mode
force: false # enable force mode, which does not ask any questions
library: # absolute path to the activity library
pretend: false # pretend mode, simulates all commands, but does not persist changes
verbose: false # verbose mode, displays more log information

pluginpath: # list of additional plugin paths, separated by whitespace

# database configuration

db:
  index: false

# configuration for printing activity/resource information

formats:
  locale: 'en'
  date: medium # allowed values: short, medium, long, full
  datetime: medium # allowed values: short, medium, long, full
  time: medium # allowed values: short, medium, long, full
  timedelta: short  # allowed values: narrow, short, long
  list:
    default: id name type starttime_local uid uids
  show:
    default: id name type starttime_local timezone duration distance
    all:

# experimental: allow predefined filters

filters:
  default:

import:
  range: 90 # number of days to fetch activities from (today to -90 days), lowering will speed up import command
  first_year: 2000 # year to start from when fetching all activities, most likely there's nothing before 2000

# gpx parser configuration

gpx:
  parser: gpxpy # allowed values: internal, gpxpy, currently ignored

# configuration for built-in plugins
plugins:

  bikecitizens:
    enabled: true
    username:
    password:

  icons:
    enabled: false

  keywords:
    enabled: true

  local:
    enabled: true

  polar:
    enabled: true
    username:
    password:

  strava:
    enabled: true
    username:
    password:
    client_id:
    client_secret:

  stravaweb:
    enabled: false

  waze:
    enabled: true
    field_size_limit: 131072
