
plugins:

  bikecitizens:
    last_fetch:
    last_download:

  polar:
    last_fetch:
    last_download:

  strava:
    access_token:
    refresh_token:
    expires_at:
    last_fetch:
    last_download:

  waze:
    fetch:
      takeouts:
